version: '3.0'

services:
  extrator_tabela:
    container_name: extrator_tabela
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    networks:
      - network_public 
        
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.textract.rule=Host(`textract.megaflow.work`)"
      - "traefik.http.routers.textract.entrypoints=websecure"      
      - "traefik.http.routers.textract.tls.certresolver=letsencryptresolver"
      - "traefik.http.services.textract.loadbalancer.server.port=5000"

    # 2. LIMITES DE RECURSOS (Mantenha se desejar, mas as labels saíram daqui)
    deploy:
      resources:
        limits:
          memory: 2048M
          cpus: "1.0"

networks:
  network_public:
    external: true